[build]
command = "turbo run build:astro"
publish = "apps/web/dist"

[dev]
command = "turbo run dev:astro"
targetPort = 7474
autoLaunch = false
framework = "#custom"
port = 8888

[images]
remote_images = ["https://cdn.sanity.io/images/okri8xbn/production/.*"]
