name: Trigger Netlify Build

on:
  schedule:
    # Runs every 3 hours
    - cron: "0 */3 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger_build:
    name: Trigger Netlify Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Netlify Build Hook
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
